spring:
  datasource:
    #    url:  jdbc:mysql://localhost:3306/kando_log?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    url:  jdbc:mysql://192.168.50.81:3306/dispatcher?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Kando@2020.
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    host: 192.168.50.10
    port: 6379
    timeout: 10000


